apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    {{- include "users.labels" . | nindent 4 }}
  app.kubernetes.io/component: users
spec:
  replicas: {{ .Values.users.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: users
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: users
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: users
          image: {{ .Values.users.image }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000