apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "users.labels" . | nindent 4 }}
type: Opaque
data:
  users_db_url: {{ .Values.usersMongoUrl | b64enc }}